### ISSUE TITLE
some errors occur while doing 'npm run build'

### ISSUE THREAD

**Issue by xiangZgnaix** [SAHX/SAHX-Admin#2]
Hello!Now days when i use your package to develop my project, it shows erros has occur.The detail is behind
`npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "wp"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! SAHX-Admin@1.0.0 wp: `webpack -w`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the SAHX-Admin@1.0.0 wp script 'webpack -w'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the SAHX-Admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -w
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs SAHX-Admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls SAHX-Admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xiangz/liangcai/admin-ui/npm-debug.log`

can you help me?
thanks!

**Comment by SAHX** [comment]
你好，你要确定一下webpck是否正常安装了？
