### ISSUE TITLE
部署好了npm start 起来了，浏览器控制台报错，页面空白

### ISSUE THREAD

**Issue by wangwenfan** [SAHX/SAHX-Admin#4]
![image](https://user-images.githubusercontent.com/17559363/42881684-7bcf62c2-8aca-11e8-92bf-e3f4bd91cff8.png)

**Comment by SAHX** [comment]
你好，感谢反馈问题，这个错误是由于vee-validate版本问题，已经解决了，请重新拉取代码，npm install一下，若还有问题，欢迎随时反馈。
